//
// Created by lilmc on 6/11/2026.
//

#ifndef PERSONAL_INFORMATION_PROCESSOR_PERSONAL_INFO_HPP
#define PERSONAL_INFORMATION_PROCESSOR_PERSONAL_INFO_HPP


class personal_info {
};


#endif //PERSONAL_INFORMATION_PROCESSOR_PERSONAL_INFO_HPP
